# Generated by Django 2.1.7 on 2019-03-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='main_image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='posts/%Y/%m/%d/'),
        ),
    ]
