# Generated by Django 2.1.7 on 2019-03-25 18:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
