version: '3'

services:
  python: &python
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    environment:
    - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - cisco-zntu
    depends_on:
      - postgres
      - rabbitmq
      - celery_worker
    restart: unless-stopped
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-wf23hdf9gfh}
      PGDATA: /data/postgres
      # POSTGRES_DB: ${POSTGRES_DB:-cisco_blog}
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - cisco-zntu
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - cisco-zntu
    restart: unless-stopped
  rabbitmq:
    container_name: dev_rabbit
    hostname: rabbit
    image: rabbitmq:3.6.6-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cisco-zntu
  celery_worker:
    <<: *python
    # command: celery -A tickets worker --loglevel=info
    ports: []
    networks:
      - cisco-zntu
    depends_on:
      - rabbitmq
      - postgres
    restart: unless-stopped

networks:
  cisco-zntu:
    driver: bridge

volumes:
  postgres:
  pgadmin:
