# Generated by Django 2.1.7 on 2019-03-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='upload/main/')),
                ('on_banner', models.BooleanField(default=False)),
            ],
        ),
    ]
